runtime: php74
# api_version: 1

# runtime_config:
#   document_root: Online forum application

handlers:
# - url: /(.+\.(gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg)$

# - url: /(.+\.(php))$
#   script: auto 

# - url: /Online forum application/Login page/.* 
#   script: Login.php
  
# - url: /.* 
#   script: auto

    
# - url: /Login page/.php*
#   script: auto

      
# - url: /Online forum application/Register page/Register.php
#   script: auto

- url: /(.+\.php)$
  script: auto


# entrypoint:
#   server index.php

  
